spring.application.name=course-api
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/fsad_university
spring.datasource.username=root
spring.datasource.password=Poojitha@10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true